package me.hch.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-03-30T23:17:34.419+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebServiceClient(name = "HelloServiceImplService", 
                  wsdlLocation = "file:/E:/pt/ws320/src/main/webapp/css/ws320.wsdl11.wsdl",
                  targetNamespace = "http://service.hch.me/") 
public class HelloServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.hch.me/", "HelloServiceImplService");
    public final static QName HelloServiceImplPort = new QName("http://service.hch.me/", "HelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/pt/ws320/src/main/webapp/css/ws320.wsdl11.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/pt/ws320/src/main/webapp/css/ws320.wsdl11.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Ws320
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public Ws320 getHelloServiceImplPort() {
        return super.getPort(HelloServiceImplPort, Ws320.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ws320
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public Ws320 getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServiceImplPort, Ws320.class, features);
    }

}
