package me.hch.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-02T17:21:53.433+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://service.hch.me/", name = "Ws320")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Ws320 {

    @WebResult(name = "NotifyHospInfoRsp", targetNamespace = "http://service.hch.me/", partName = "parameters")
    @Action(input = "http://service.hch.me/Ws320/NotifyHospInfoReq", output = "http://service.hch.me/Ws320/NotifyHospInfoRsp")
    @WebMethod(operationName = "NotifyHospInfo")
    public NotifyHospInfoRsp notifyHospInfo(
            @WebParam(partName = "parameters", name = "NotifyHospInfoReq", targetNamespace = "http://service.hch.me/")
            NotifyHospInfoReq parameters
    );

    @WebResult(name = "GetHospInfoRsp", targetNamespace = "http://service.hch.me/", partName = "parameters")
    @Action(input = "http://service.hch.me/Ws320/GetHospInfoRequest", output = "http://service.hch.me/Ws320/GetHospInfoResponse")
    @WebMethod(operationName = "GetHospInfo")
    public GetHospInfoRsp getHospInfo(
            @WebParam(partName = "parameters", name = "GetHospInfoReq", targetNamespace = "http://service.hch.me/")
            GetHospInfoReq parameters
    );

    @WebResult(name = "RegisterRsp", targetNamespace = "http://service.hch.me/", partName = "parameters")
    @Action(input = "http://service.hch.me/Ws320/RegisterReq", output = "http://service.hch.me/Ws320/RegisterRsp")
    @WebMethod(operationName = "Register")
    public RegisterRsp register(
            @WebParam(partName = "parameters", name = "RegisterReq", targetNamespace = "http://service.hch.me/")
            RegisterReq parameters
    );

    @WebResult(name = "GetRegInfoRsp", targetNamespace = "http://service.hch.me/", partName = "parameters")
    @Action(input = "http://service.hch.me/Ws320/GetRegInfoReq", output = "http://service.hch.me/Ws320/GetRegInfoRsp")
    @WebMethod(operationName = "GetRegInfo")
    public GetRegInfoRsp getRegInfo(
            @WebParam(partName = "parameters", name = "GetRegInfoReq", targetNamespace = "http://service.hch.me/")
            GetRegInfoReq parameters
    );

    @WebResult(name = "GetRegPoolRsp", targetNamespace = "http://service.hch.me/", partName = "parameters")
    @Action(input = "http://service.hch.me/Ws320/GetRegPoolReq", output = "http://service.hch.me/Ws320/GetRegPoolRsp")
    @WebMethod(operationName = "GetRegPool")
    public GetRegPoolRsp getRegPool(
            @WebParam(partName = "parameters", name = "GetRegPoolReq", targetNamespace = "http://service.hch.me/")
            GetRegPoolReq parameters
    );
}
